In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('./data/fraudTest.csv', index_col=0)

In [4]:
df.head(2)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 555719 entries, 0 to 555718
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  555719 non-null  object
 1   cc_num                 555719 non-null  int64
 2   merchant               555719 non-null  object
 3   category               555719 non-null  object
 4   amt                    555719 non-null  float64
 5   first                  555719 non-null  object
 6   last                   555719 non-null  object
 7   gender                 555719 non-null  object
 8   street                 555719 non-null  object
 9   city                   555719 non-null  object
 10  state                  555719 non-null  object
 11  zip                    555719 non-null  int64
 12  lat                    555719 non-null  float64
 13  long                   555719 non-null  float64
 14  city_pop               555719 non-null  int64
 15  job                    555719 non-null  object
 16  dob                    555719 non-null  object
 17  trans_num              555719 non-null  object
 18  unix_time              555719 non-null  int64
 19  merch_lat              555719 non-null  float64
 20  merch_long             555719 non-null  float64
 21  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(5), object(12)
memory usage: 97.5+ MB

In [6]:
df['is_fraud'].value_counts()

is_fraud
0    553574
1      2145
Name: count, dtype: int64

# Data Dictionary

* `trans_date_trans_time` - 거래 타임스탬프 (날짜 및 시간)
* `cc_num` - 신용카드 번호
* `merchant` - 가맹점 이름
* `category` - 거래 카테고리
* `amt` - 거래 금액
* `first` - 카드 소지자 이름 (이름)
* `last` - 카드 소지자 이름 (성)
* `gender` - 카드 소지자의 성별
* `street` - 카드 소시자 주소
* `city` - 카드 소지자 도시
* `state` - 카드 소지자 주 (state)
* `zip` - 카드 소지자 우편번호
* `lat` - 카드 소지자 위도
* `long` - 카드 소지자 경도
* `city_pop` - 도시 인구수
* `job` - 카드 소지자의 직업
* `dob` - 카드 소지자의 생년월일
* `trans_num` - 거래 고유 번호
* `unix_time` - 유닉스 시간
* `merch_lat` - 가맹점 위도
* `merch_long` - 가맹점 경도
* `is_fraud` - 사기 여부 (1: 사기, 0: 정상)

데이터 제거

- cc_num
- zip
- trans_num
- first, last
- merchant
- street
- unix_time
- state

In [7]:
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])

In [8]:
# trans_date_trans_time 에서 시간, 분, 요일, 년도, 월, 일 추출 

df['year'] = df['trans_date_trans_time'].dt.year
df['month'] = df['trans_date_trans_time'].dt.month
df['day'] = df['trans_date_trans_time'].dt.day
df['hour'] = df['trans_date_trans_time'].dt.hour
df['day_of_week'] = df['trans_date_trans_time'].dt.dayofweek

In [9]:
def season(x):
    if x in [1 ,2 ,3]:
        return 1
    if x in [4 ,5 ,6]:
        return 2
    if x in [7 ,8 ,9]:
        return 3
    if x in [10 ,11 ,12]:
        return 4

df['season'] = df['month'].apply(season)

In [10]:
df.head(2)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,year,month,day,hour,day_of_week,season
0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0,2020,6,21,12,6,2
1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0,2020,6,21,12,6,2

In [11]:
# dob에서 나이 추출, age는 거래당시의 나이

df['dob'] = pd.to_datetime(df['dob'])

from dateutil.relativedelta import relativedelta

def calculate_age(born, trans_date):
    return relativedelta(trans_date, born).years

df['age'] = df.apply(lambda x: calculate_age(x['dob'], x['trans_date_trans_time']), axis=1)

In [12]:
df.head(2)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,year,month,day,hour,day_of_week,season,age
0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0,2020,6,21,12,6,2,52
1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0,2020,6,21,12,6,2,30

In [13]:
# 전처리 이후 필요없는 변수(trans_date_trans_time, dob) 제거

df = df.drop(['trans_date_trans_time', 'dob'], axis=1)

In [14]:
df.head(2)

,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,trans_num,unix_time,merch_lat,merch_long,is_fraud,year,month,day,hour,day_of_week,season,age
0,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0,2020,6,21,12,6,2,52
1,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0,2020,6,21,12,6,2,30

In [15]:
# 이름 및 거래 고유 번호 제거

df_non_name = df.drop(['cc_num', 'first', 'last', 'street', 'zip', 'trans_num'], axis=1)

In [16]:
df_non_name.head(2)

,merchant,category,amt,gender,city,state,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud,year,month,day,hour,day_of_week,season,age
0,fraud_Kirlin and Sons,personal_care,2.86,M,Columbia,SC,33.9659,-80.9355,333497,Mechanical engineer,1371816865,33.986391,-81.200714,0,2020,6,21,12,6,2,52
1,fraud_Sporer-Keebler,personal_care,29.84,F,Altonah,UT,40.3207,-110.4360,302,"Sales professional, IT",1371816873,39.450498,-109.960431,0,2020,6,21,12,6,2,30

In [17]:
df_non_name.info()

<class 'pandas.core.frame.DataFrame'>
Index: 555719 entries, 0 to 555718
Data columns (total 21 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   merchant     555719 non-null  object
 1   category     555719 non-null  object
 2   amt          555719 non-null  float64
 3   gender       555719 non-null  object
 4   city         555719 non-null  object
 5   state        555719 non-null  object
 6   lat          555719 non-null  float64
 7   long         555719 non-null  float64
 8   city_pop     555719 non-null  int64
 9   job          555719 non-null  object
 10  unix_time    555719 non-null  int64
 11  merch_lat    555719 non-null  float64
 12  merch_long   555719 non-null  float64
 13  is_fraud     555719 non-null  int64
 14  year         555719 non-null  int32
 15  month        555719 non-null  int32
 16  day          555719 non-null  int32
 17  hour         555719 non-null  int32
 18  day_of_week  555719 non-null  int32
 19  season       555719 non-null  int64
 20  age          555719 non-null  int64
dtypes: float64(5), int32(5), int64(5), object(6)
memory usage: 82.7+ MB

In [18]:
def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371  # 지구 반지름 (km 단위)
    
    lat1_rad, lon1_rad = np.radians(lat1), np.radians(lon1)
    lat2_rad, lon2_rad = np.radians(lat2), np.radians(lon2)
    
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad
    
    a = np.sin(dlat / 2)**2 + np.cos(lat1_rad) * np.cos(lat2_rad) * np.sin(dlon / 2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    return R * c

In [19]:
df_non_name['distance_km'] = haversine_distance(df_non_name['lat'], df_non_name['long'], df_non_name['merch_lat'], df_non_name['merch_long'])

In [20]:
df_non_name.head(2)

,merchant,category,amt,gender,city,state,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud,year,month,day,hour,day_of_week,season,age,distance_km
0,fraud_Kirlin and Sons,personal_care,2.86,M,Columbia,SC,33.9659,-80.9355,333497,Mechanical engineer,1371816865,33.986391,-81.200714,0,2020,6,21,12,6,2,52,24.561462
1,fraud_Sporer-Keebler,personal_care,29.84,F,Altonah,UT,40.3207,-110.4360,302,"Sales professional, IT",1371816873,39.450498,-109.960431,0,2020,6,21,12,6,2,30,104.925092

In [37]:
df_non_name.nunique()

merchant          693
category           14
amt             37256
gender              2
city              849
state              50
lat               910
long              910
city_pop          835
job               478
unix_time      544760
merch_lat      546490
merch_long     551770
is_fraud            2
year                1
month               7
day                31
hour               24
day_of_week         7
season              3
age                82
distance_km    555719
dtype: int64

In [21]:
df_final = df_non_name.drop(['lat', 'long', 'merch_lat', 'merch_long', 'year'], axis=1)

In [22]:
df_final.head(2)

,merchant,category,amt,gender,city,state,city_pop,job,unix_time,is_fraud,month,day,hour,day_of_week,season,age,distance_km
0,fraud_Kirlin and Sons,personal_care,2.86,M,Columbia,SC,333497,Mechanical engineer,1371816865,0,6,21,12,6,2,52,24.561462
1,fraud_Sporer-Keebler,personal_care,29.84,F,Altonah,UT,302,"Sales professional, IT",1371816873,0,6,21,12,6,2,30,104.925092

In [23]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 555719 entries, 0 to 555718
Data columns (total 17 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   merchant     555719 non-null  object
 1   category     555719 non-null  object
 2   amt          555719 non-null  float64
 3   gender       555719 non-null  object
 4   city         555719 non-null  object
 5   state        555719 non-null  object
 6   city_pop     555719 non-null  int64
 7   job          555719 non-null  object
 8   unix_time    555719 non-null  int64
 9   is_fraud     555719 non-null  int64
 10  month        555719 non-null  int32
 11  day          555719 non-null  int32
 12  hour         555719 non-null  int32
 13  day_of_week  555719 non-null  int32
 14  season       555719 non-null  int64
 15  age          555719 non-null  int64
 16  distance_km  555719 non-null  float64
dtypes: float64(2), int32(4), int64(5), object(6)
memory usage: 67.8+ MB

# 로지스틱회귀 - 통계적 검증

In [24]:
from sklearn.preprocessing import StandardScaler

df_final['city_pop'] = df_final['city_pop'].apply(np.log)

num_cols = ['amt', 'city_pop', 'age', 'unix_time', 'distance_km']

scaler = StandardScaler()
df_final[num_cols] = scaler.fit_transform(df_final[num_cols])

In [25]:
def reduce_categories(df, col_list, top_n=30):
    df = df.copy()
    for col in col_list:
        top_cats = df[col].value_counts().nlargest(top_n).index
        df[col] = df[col].apply(lambda x: x if x in top_cats else 'etc')
    return df

In [26]:
cat_cols = ['merchant', 'city', 'job', 'state', 'category', 'gender']
df_final = reduce_categories(df_final, cat_cols, top_n=30)

In [27]:
other_cols = ['month', 'day', 'hour', 'day_of_week', 'season']

In [28]:
target = 'is_fraud'
features = num_cols + cat_cols + other_cols
formula = f"{target} ~ " + " + ".join([
    f"C({col})" if col in cat_cols else col for col in features
])

In [29]:
formula

'is_fraud ~ amt + city_pop + age + unix_time + distance_km + C(merchant) + C(city) + C(job) + C(state) + C(category) + C(gender) + month + day + hour + day_of_week + season'

In [30]:
df_final.head()

,merchant,category,amt,gender,city,state,city_pop,job,unix_time,is_fraud,month,day,hour,day_of_week,season,age,distance_km
0,etc,personal_care,-0.424463,M,etc,SC,1.782476,etc,-1.703871,0,6,21,12,6,2,0.321790,-1.770215
1,etc,personal_care,-0.252337,F,etc,etc,-1.077257,etc,-1.703869,0,6,21,12,6,2,-0.940243,0.989805
2,etc,health_fitness,-0.179353,F,etc,NY,0.856520,"Librarian, public",-1.703865,0,6,21,12,6,2,0.149695,-0.584703
3,etc,misc_pos,-0.059605,M,etc,FL,1.045175,etc,-1.703861,0,6,21,12,6,2,-0.825513,-1.662474
4,etc,travel,-0.422358,M,etc,MI,-0.540162,etc,-1.703861,0,6,21,12,6,2,1.010171,0.969542

In [31]:
df_final.corr(numeric_only=True).abs()

,amt,city_pop,unix_time,is_fraud,month,day,hour,day_of_week,season,age,distance_km
amt,1.000000,0.010262,0.000974,0.182267,0.000717,0.000829,0.029860,0.003414,0.000550,0.012864,0.000767
city_pop,0.010262,1.000000,0.001001,0.000890,0.001491,0.002331,0.030808,0.003284,0.002261,0.147743,0.021175
unix_time,0.000974,0.001001,1.000000,0.013066,0.988955,0.044348,0.000304,0.009987,0.890485,0.006830,0.000419
is_fraud,0.182267,0.000890,0.013066,1.000000,0.011748,0.009203,0.011686,0.009365,0.008153,0.007334,0.000233
month,0.000717,0.001491,0.988955,0.011748,1.000000,0.104058,0.004995,0.004090,0.908028,0.007967,0.000382
day,0.000829,0.002331,0.044348,0.009203,0.104058,1.000000,0.000161,0.038866,0.139583,0.002373,0.000218
hour,0.029860,0.030808,0.000304,0.011686,0.004995,0.000161,1.000000,0.001516,0.006385,0.173695,0.000527
day_of_week,0.003414,0.003284,0.009987,0.009365,0.004090,0.038866,0.001516,1.000000,0.012446,0.004135,0.000930
season,0.000550,0.002261,0.890485,0.008153,0.908028,0.139583,0.006385,0.012446,1.000000,0.007745,0.000352
age,0.012864,0.147743,0.006830,0.007334,0.007967,0.002373,0.173695,0.004135,0.007745,1.000000,0.003165
distance_km,0.000767,0.021175,0.000419,0.000233,0.000382,0.000218,0.000527,0.000930,0.000352,0.003165,1.000000

In [32]:
print(df_final.nunique())

merchant           31
category           14
amt             37256
gender              2
city               31
state              31
city_pop          835
job                31
unix_time      544760
is_fraud            2
month               7
day                31
hour               24
day_of_week         7
season              3
age                82
distance_km    555719
dtype: int64

In [33]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 555719 entries, 0 to 555718
Data columns (total 17 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   merchant     555719 non-null  object
 1   category     555719 non-null  object
 2   amt          555719 non-null  float64
 3   gender       555719 non-null  object
 4   city         555719 non-null  object
 5   state        555719 non-null  object
 6   city_pop     555719 non-null  float64
 7   job          555719 non-null  object
 8   unix_time    555719 non-null  float64
 9   is_fraud     555719 non-null  int64
 10  month        555719 non-null  int32
 11  day          555719 non-null  int32
 12  hour         555719 non-null  int32
 13  day_of_week  555719 non-null  int32
 14  season       555719 non-null  int64
 15  age          555719 non-null  float64
 16  distance_km  555719 non-null  float64
dtypes: float64(5), int32(4), int64(2), object(6)
memory usage: 67.8+ MB

## 다중공산성 진단

In [50]:
# 다중공산성 문제 진단 - VIF(분산 팽창 인수) 확인
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

df_final_x = df_final.drop(['is_fraud'], axis = 1)
df_final_x = pd.get_dummies(df_final_x, dtype=int, drop_first=True)

# bool 타입 칼럼 int로 변환
for col in df_final_x.select_dtypes(include='bool').columns:
    df_final_x[col] = df_final_x[col].astype(int)

# 분산이 0인 컬럼 제거
singular_cols = [col for col in df_final_x.columns if df_final_x[col].nunique() == 1]
if len(singular_cols) > 0:
    print(f"\n--- Removing columns with zero variance: {singular_cols} ---")
    df_final_x = df_final_x.drop(columns=singular_cols)

# VIF 계산 시작
print("\n--- VIF (Variance Inflation Factor) ---")
vif_data = pd.DataFrame()
vif_data["feature"] = df_final_x.columns

# 모든 독립 변수에 대해 VIF 계산
vif_values = []
for i in range(df_final_x.shape[1]):
    try:
        vif_values.append(variance_inflation_factor(df_final_x.values, i))
    except Exception as e:
        # 혹시 모를 다른 오류 처리 (예: 여전히 분산 0인 컬럼 등)
        print(f"Error calculating VIF for column {df_final_x.columns[i]}: {e}")
        vif_values.append(np.nan) # 오류 발생 시 NaN으로 표시

vif_data["VIF"] = vif_values
print(vif_data.sort_values(by="VIF", ascending=False))

--- VIF (Variance Inflation Factor) ---
                        feature         VIF
3                         month  894.506134
84                     city_etc  420.321273
7                        season  199.718672
144                     job_etc  169.320379
2                     unix_time   29.767331
..                          ...         ...
37    merchant_fraud_Schumm PLC    1.021171
24   merchant_fraud_Kilback LLC    1.020837
12     merchant_fraud_Boyer PLC    1.020631
27      merchant_fraud_Kuhn LLC    1.020307
9                   distance_km    1.004552

[145 rows x 2 columns]

In [57]:
pd.set_option('display.max_rows', 200)

In [58]:
vif_data.sort_values(by="VIF", ascending=False).reset_index(drop=True)

                                               feature         VIF
0                                                month  894.506134
1                                             city_etc  420.321273
2                                               season  199.718672
3                                              job_etc  169.320379
4                                            unix_time   29.767331
5                                                 hour    9.552664
6                                            state_etc    7.423131
7                                                  day    6.659125
8                                             state_TX    4.181406
9                               category_gas_transport    3.825662
10                                            state_PA    3.737545
11                                            state_NY    3.723024
12                                     city_Birmingham    3.547179
13                                        city_Burbank    3.273777
14                                    city_San Antonio    3.111761
15                                        job_Musician    3.086679
16                                      city_Cleveland    3.014051
17                                        city_Phoenix    2.945572
18                                       city_Meridian    2.901012
19                                          city_Utica    2.882771
20                                         city_Thomas    2.852138
21                                         city_Conway    2.837721
22                                        city_Houston    2.827676
23                                            state_FL    2.809085
24                                         city_Warren    2.802455
25                                            state_CA    2.780457
26                                         city_Fulton    2.765931
27                                category_grocery_pos    2.739662
28                                            state_MI    2.724121
29                                   city_Indianapolis    2.700834
30                             job_Exhibition designer    2.675370
31                                        city_Brandon    2.612285
32                                         day_of_week    2.574825
33                                            state_OH    2.571017
34                                         city_Naples    2.567363
35                                  city_Fort Washakie    2.560400
36                                         city_Orient    2.540237
37                               job_Film/video editor    2.535166
38                                        city_Arcadia    2.529618
39                                         city_Lahoma    2.505545
40                                       city_Lakeland    2.503955
41                         job_Copywriter, advertising    2.478232
42                        job_Environmental consultant    2.475985
43                                            state_IL    2.463975
44                                         city_Dallas    2.431121
45                                        city_Detroit    2.415025
46                               job_Financial adviser    2.413164
47                                     city_Huntsville    2.411449
48                        job_Surveyor, land/geomatics    2.410912
49                      job_Designer, ceramics/pottery    2.397389
50                                   city_Philadelphia    2.380717
51                                  city_Edisto Island    2.380082
52                                        city_Andrews    2.376472
53                                 job_Naval architect    2.373611
54                                         city_Hudson    2.337148
55                              job_Materials engineer    2.328845
56                                       category_home    2.326811
57                                     city_Washington    2.316858
58                                            state_WA    2.310001
59                               category_shopping_pos    2.290033
60                               job_Building surveyor    2.272381
61                   job_Clothing/textile technologist    2.250367
62                                   city_Clarks Mills    2.248462
63                               job_Systems developer    2.245223
64                     job_Scientist, research (maths)    2.241445
65                                            state_MO    2.241251
66                                  category_kids_pets    2.234623
67                                             job_Sub    2.231238
68                         job_Chief Executive Officer    2.216289
69                                      job_IT trainer    2.213072
70                                      job_Podiatrist    2.201459
71             job_Chartered public finance accountant    2.185424
72                                       job_Paramedic    2.176943
73                        job_Magazine features editor    2.174676
74                         job_Scientist, audiological    2.172353
75                                            state_IN    2.132172
76                               category_shopping_net    2.114949
77                                            state_SC    2.099815
78                                            gender_M    2.093388
79                                       job_Barrister    2.093230
80                                            state_AR    2.088886
81                                            state_OK    2.083186
82                                     job_Comptroller    2.052550
83                                            state_NC    2.047571
84                                            state_MN    2.029464
85                                            state_WV    2.028452
86                                 job_Mining engineer    2.021590
87                              category_personal_care    2.011154
88                          job_Audiological scientist    1.996583
89                                category_food_dining    1.990348
90                                    job_Immunologist    1.984854
91                               job_Librarian, public    1.981709
92                                            state_IA    1.959967
93   job_Historic buildings inspector/conservation ...    1.951381
94                                   category_misc_pos    1.951143
95                             category_health_fitness    1.946395
96                                            state_VA    1.937887
97                                            state_WI    1.932955
98                                            state_KY    1.932275
99                                            state_KS    1.861665
100                                           state_WY    1.854986
101                                           state_GA    1.842132
102                                           state_MD    1.834177
103                                  category_misc_net    1.825412
104                                           state_NJ    1.765395
105                                           state_NE    1.765370
106                                           state_MS    1.717994
107                               category_grocery_net    1.668061
108                                           state_LA    1.652734
109                                           city_pop    1.522945
110                                    category_travel    1.446401
111                                                age    1.256881
112                                            weights    1.056952
113                                                amt    1.051997
114                           merchant_fraud_Emard Inc    1.042872
115                   merchant_fraud_Parisian and Sons    1.042023
116                      merchant_fraud_Corwin-Collins    1.041135
117            merchant_fraud_Streich, Hansen and Veum    1.040846
118       merchant_fraud_Robel, Cummerata and Prosacco    1.040706
119         merchant_fraud_Schaefer, McGlynn and Bosco    1.040644
120              merchant_fraud_Zieme, Bode and Dooley    1.040535
121                          merchant_fraud_Huels-Hahn    1.040434
122                           merchant_fraud_Kling Inc    1.040343
123            merchant_fraud_Raynor, Feest and Miller    1.040279
124             merchant_fraud_Reilly, Heaney and Cole    1.040086
125                 merchant_fraud_Ledner-Pfannerstill    1.040046
126                         merchant_fraud_Mraz-Herzog    1.039957
127         merchant_fraud_Raynor, Reinger and Hagenes    1.039951
128                       merchant_fraud_Koss and Sons    1.039941
129       merchant_fraud_Eichmann, Bogan and Rodriguez    1.039931
130       merchant_fraud_Greenholt, Jacobi and Gleason    1.039800
131                          merchant_fraud_Harris Inc    1.039799
132                    merchant_fraud_Erdman-Kertzmann    1.039642
133                     merchant_fraud_Friesen-D'Amore    1.039587
134                     merchant_fraud_Prohaska-Murray    1.039504
135                     merchant_fraud_Brekke and Sons    1.039461
136                           merchant_fraud_Bins-Rice    1.039456
137                        merchant_fraud_Torp-Labadie    1.039441
138                         merchant_fraud_Cormier LLC    1.021610
139                       merchant_fraud_Dickinson Ltd    1.021261
140                          merchant_fraud_Schumm PLC    1.021171
141                         merchant_fraud_Kilback LLC    1.020837
142                           merchant_fraud_Boyer PLC    1.020631
143                            merchant_fraud_Kuhn LLC    1.020307
144                                        distance_km    1.004552

In [59]:
pd.reset_option('display.max_rows')

## 범주형 변수 우도비 검정

In [76]:
all_model_features = num_cols + cat_cols + other_cols

In [74]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

# 가중치 지정
df_final['weights'] = df_final['is_fraud'].apply(lambda x: 258 if x == 1 else 1)

full_model = smf.glm(formula=formula, data=df_final, family=sm.families.Binomial())
full_result = full_model.fit(weights=df_final['weights'])
full_result.summary().tables[0] # 첫 번째 요약 테이블만 출력하여 간결하게

In [78]:
from scipy import stats

# 각 범주형 변수에 대한 우도비 검정 (Likelihood Ratio Test)
categorical_features_to_test = ['merchant', 'city', 'job', 'state', 'category', 'gender']

for feature in categorical_features_to_test:
    print(f"\n[검정 중]: '{feature}' 변수")

    # 현재 범주형 변수를 제외한 축소 모델(Reduced Model)의 포뮬러 구성
    reduced_features_for_formula = [f for f in all_model_features if f != feature] # C() 래핑 전의 feature 이름으로 제거
    reduced_formula = f"{target} ~ " + " + ".join([
        f"C({col})" if col in cat_cols else col # 원래 제공된 코드처럼 cat_cols만 C()
        for col in reduced_features_for_formula
    ])

    # 축소 모델 학습 (동일한 weights 적용)
    try:
        reduced_model = smf.glm(formula=reduced_formula, data=df_final, family=sm.families.Binomial())
        reduced_result = reduced_model.fit(weights=df_final['weights'])

        # LRT 통계량 계산
        lrt_statistic = 2 * (full_result.llf - reduced_result.llf)

        # 자유도(Degrees of Freedom) 차이 계산
        df_diff = len(full_result.params) - len(reduced_result.params)

        # p-value 계산
        lrt_pvalue = stats.chi2.sf(lrt_statistic, df_diff)

        print(f"  - LRT 통계량: {lrt_statistic:.4f}")
        print(f"  - 자유도 (df): {df_diff}")
        print(f"  - LRT p-value: {lrt_pvalue:.6f}")

        if lrt_pvalue < 0.05:
            print(f"  결론: '{feature}' 변수는 통계적으로 유의미합니다 (p < 0.05). 모델에 유의미한 기여를 합니다.")
        else:
            print(f"  결론: '{feature}' 변수는 통계적으로 유의미하지 않습니다 (p >= 0.05). 모델에서 제거하는 것을 고려할 수 있습니다.")
    except Exception as e:
        print(f"  오류 발생: '{feature}' 변수에 대한 축소 모델 학습 중 문제가 발생했습니다: {e}")
        print("  (이 오류는 데이터의 완전 분리, 작은 클래스 수, 또는 기타 수렴 문제로 인해 발생할 수 있습니다. 특히 'etc' 범주가 생긴 후 해당 범주만으로 클래스가 분리될 경우 발생하기 쉽습니다.)")
        print("  해결책: 범주 통합 시 top_n 값 조정, 또는 분리 문제를 일으키는 데이터 포인트 확인, 또는 sklearn.linear_model.LogisticRegression과 같은 정규화 모델 고려.")

[검정 중]: 'merchant' 변수
  - LRT 통계량: 26.4509
  - 자유도 (df): 30
  - LRT p-value: 0.651932
  결론: 'merchant' 변수는 통계적으로 유의미하지 않습니다 (p >= 0.05). 모델에서 제거하는 것을 고려할 수 있습니다.

[검정 중]: 'city' 변수
  - LRT 통계량: 417.6055
  - 자유도 (df): 30
  - LRT p-value: 0.000000
  결론: 'city' 변수는 통계적으로 유의미합니다 (p < 0.05). 모델에 유의미한 기여를 합니다.

[검정 중]: 'job' 변수
  - LRT 통계량: 384.7780
  - 자유도 (df): 30
  - LRT p-value: 0.000000
  결론: 'job' 변수는 통계적으로 유의미합니다 (p < 0.05). 모델에 유의미한 기여를 합니다.

[검정 중]: 'state' 변수
  - LRT 통계량: 244.5449
  - 자유도 (df): 30
  - LRT p-value: 0.000000
  결론: 'state' 변수는 통계적으로 유의미합니다 (p < 0.05). 모델에 유의미한 기여를 합니다.

[검정 중]: 'category' 변수
  - LRT 통계량: 2491.9353
  - 자유도 (df): 13
  - LRT p-value: 0.000000
  결론: 'category' 변수는 통계적으로 유의미합니다 (p < 0.05). 모델에 유의미한 기여를 합니다.

[검정 중]: 'gender' 변수
  오류 발생: 'gender' 변수에 대한 축소 모델 학습 중 문제가 발생했습니다:
  (이 오류는 데이터의 완전 분리, 작은 클래스 수, 또는 기타 수렴 문제로 인해 발생할 수 있습니다. 특히 'etc' 범주가 생긴 후 해당 범주만으로 클래스가 분리될 경우 발생하기 쉽습니다.)
  해결책: 범주 통합 시 top_n 값 조정, 또는 분리 문제를 일으키는 데이터 포인트 확인, 또는 sklearn.linear_model.LogisticRegression과 같은 정규화 모델 고려.

## pvalue와 오즈비 확인

In [34]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

# 가중치 지정
df_final['weights'] = df_final['is_fraud'].apply(lambda x: 258 if x == 1 else 1)

# 모델 생성
model = smf.glm(formula=formula, data=df_final, 
                family=sm.families.Binomial())

# 학습 (weights 적용)
result = model.fit(weights=df_final['weights'])

In [35]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:               is_fraud   No. Observations:               555719
Model:                            GLM   Df Residuals:                   555574
Model Family:                Binomial   Df Model:                          144
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -11083.
Date:                Sun, 29 Jun 2025   Deviance:                       22166.
Time:                        21:58:41   Pearson chi2:                 2.51e+15
No. Iterations:                    30   Pseudo R-squ. (CS):            0.01066
Covariance Type:            nonrobust
===============================================================================================================================
                                                                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------
Intercept                                                     283.5971     28.646      9.900      0.000     227.451     339.743
C(merchant)[T.fraud_Bins-Rice]                                  0.2038      0.513      0.397      0.691      -0.802       1.209
C(merchant)[T.fraud_Boyer PLC]                                  0.2419      0.290      0.834      0.404      -0.327       0.810
C(merchant)[T.fraud_Brekke and Sons]                           -0.5572      0.716     -0.778      0.437      -1.961       0.847
C(merchant)[T.fraud_Cormier LLC]                               -0.6582      0.461     -1.428      0.153      -1.562       0.245
C(merchant)[T.fraud_Corwin-Collins]                            -0.5881      0.716     -0.821      0.412      -1.992       0.816
C(merchant)[T.fraud_Dickinson Ltd]                             -1.0905      1.005     -1.086      0.278      -3.059       0.878
C(merchant)[T.fraud_Eichmann, Bogan and Rodriguez]             -0.5207      0.716     -0.727      0.467      -1.925       0.883
C(merchant)[T.fraud_Emard Inc]                                 -0.6136      0.716     -0.856      0.392      -2.018       0.791
C(merchant)[T.fraud_Erdman-Kertzmann]                          -0.5619      0.716     -0.784      0.433      -1.966       0.842
C(merchant)[T.fraud_Friesen-D'Amore]                           -0.5715      0.716     -0.798      0.425      -1.976       0.833
C(merchant)[T.fraud_Greenholt, Jacobi and Gleason]             -0.1417      0.589     -0.241      0.810      -1.296       1.012
C(merchant)[T.fraud_Harris Inc]                                -1.2836      1.007     -1.275      0.202      -3.257       0.689
C(merchant)[T.fraud_Huels-Hahn]                                -0.5379      0.716     -0.751      0.453      -1.942       0.866
C(merchant)[T.fraud_Kilback LLC]                                0.3562      0.266      1.341      0.180      -0.164       0.877
C(merchant)[T.fraud_Kling Inc]                                 -0.1503      0.589     -0.255      0.799      -1.304       1.004
C(merchant)[T.fraud_Koss and Sons]                             -0.1281      0.589     -0.217      0.828      -1.282       1.026
C(merchant)[T.fraud_Kuhn LLC]                                   0.2839      0.321      0.884      0.377      -0.346       0.914
C(merchant)[T.fraud_Ledner-Pfannerstill]                       -0.1268      0.589     -0.215      0.829      -1.281       1.027
C(merchant)[T.fraud_Mraz-Herzog]                                0.1800      0.513      0.351      0.726      -0.826       1.186
C(merchant)[T.fraud_Parisian and Sons]                          0.8991      0.353      2.549      0.011       0.208       1.590
C(merchant)[T.fraud_Prohaska-Murray]                           -0.0977      0.589     -0.166      0.868      -1.252       1.056
C(merchant)[T.fraud_Raynor, Feest and Miller]                  -1.2997      1.007     -1.291      0.197      -3.273       0.673
C(merchant)[T.fraud_Raynor, Reinger and Hagenes]               -0.5548      0.717     -0.774      0.439      -1.959       0.850
C(merchant)[T.fraud_Reilly, Heaney and Cole]                    0.0854      0.513      0.166      0.868      -0.920       1.091
C(merchant)[T.fraud_Robel, Cummerata and Prosacco]             -0.2053      0.589     -0.349      0.727      -1.359       0.949
C(merchant)[T.fraud_Schaefer, McGlynn and Bosco]               -1.2307      1.007     -1.223      0.221      -3.204       0.742
C(merchant)[T.fraud_Schumm PLC]                                -0.0746      0.338     -0.221      0.825      -0.736       0.587
C(merchant)[T.fraud_Streich, Hansen and Veum]                  -0.1997      0.589     -0.339      0.735      -1.354       0.954
C(merchant)[T.fraud_Torp-Labadie]                              -0.1129      0.589     -0.192      0.848      -1.267       1.041
C(merchant)[T.fraud_Zieme, Bode and Dooley]                    -0.6000      0.717     -0.837      0.402      -2.005       0.805
C(city)[T.Andrews]                                             -1.1400      0.572     -1.993      0.046      -2.261      -0.019
C(city)[T.Arcadia]                                              0.0908      0.456      0.199      0.842      -0.803       0.984
C(city)[T.Birmingham]                                           0.9466      0.421      2.250      0.024       0.122       1.771
C(city)[T.Brandon]                                            -27.2522   9.17e+04     -0.000      1.000    -1.8e+05     1.8e+05
C(city)[T.Burbank]                                            -27.1821   8.05e+04     -0.000      1.000   -1.58e+05    1.58e+05
C(city)[T.Clarks Mills]                                         0.7365      0.424      1.738      0.082      -0.094       1.567
C(city)[T.Cleveland]                                          -26.4388   8.89e+04     -0.000      1.000   -1.74e+05    1.74e+05
C(city)[T.Conway]                                             -50.1217   4.08e+05     -0.000      1.000   -8.01e+05       8e+05
C(city)[T.Dallas]                                               0.3560      0.481      0.740      0.459      -0.587       1.299
C(city)[T.Detroit]                                             -0.2418      0.532     -0.455      0.649      -1.284       0.801
C(city)[T.Edisto Island]                                      -26.5509   1.03e+05     -0.000      1.000   -2.01e+05    2.01e+05
C(city)[T.Fort Washakie]                                      -25.8080   9.59e+04     -0.000      1.000   -1.88e+05    1.88e+05
C(city)[T.Fulton]                                             -26.8101   9.05e+04     -0.000      1.000   -1.77e+05    1.77e+05
C(city)[T.Houston]                                            -24.7964   8.48e+04     -0.000      1.000   -1.66e+05    1.66e+05
C(city)[T.Hudson]                                             -26.6908   9.87e+04     -0.000      1.000   -1.93e+05    1.93e+05
C(city)[T.Huntsville]                                         -27.0362   9.98e+04     -0.000      1.000   -1.96e+05    1.96e+05
C(city)[T.Indianapolis]                                       -27.5162   9.24e+04     -0.000      1.000   -1.81e+05    1.81e+05
C(city)[T.Lahoma]                                             -26.6654   1.07e+05     -0.000      1.000   -2.09e+05    2.09e+05
C(city)[T.Lakeland]                                           -27.5149   1.01e+05     -0.000      1.000   -1.98e+05    1.98e+05
C(city)[T.Meridian]                                            -1.3483      0.565     -2.388      0.017      -2.455      -0.242
C(city)[T.Naples]                                             -48.0261   1.58e+06  -3.04e-05      1.000    -3.1e+06     3.1e+06
C(city)[T.Orient]                                               0.0060      0.499      0.012      0.990      -0.972       0.984
C(city)[T.Philadelphia]                                       -26.3472   9.97e+04     -0.000      1.000   -1.95e+05    1.95e+05
C(city)[T.Phoenix]                                             -0.3022      0.443     -0.681      0.496      -1.171       0.567
C(city)[T.San Antonio]                                        -25.2244    7.7e+04     -0.000      1.000   -1.51e+05    1.51e+05
C(city)[T.Thomas]                                               0.7242      0.640      1.132      0.258      -0.530       1.979
C(city)[T.Utica]                                              -26.5035   8.53e+04     -0.000      1.000   -1.67e+05    1.67e+05
C(city)[T.Warren]                                             -25.8327   8.62e+04     -0.000      1.000   -1.69e+05    1.69e+05
C(city)[T.Washington]                                          -0.0827      0.472     -0.175      0.861      -1.009       0.843
C(city)[T.etc]                                                 -0.6907      0.332     -2.082      0.037      -1.341      -0.041
C(job)[T.Audiological scientist]                               -0.0217      0.441     -0.049      0.961      -0.887       0.843
C(job)[T.Barrister]                                            -0.1955      0.500     -0.391      0.696      -1.175       0.784
C(job)[T.Building surveyor]                                    -0.0674      0.448     -0.150      0.880      -0.946       0.811
C(job)[T.Chartered public finance accountant]                  -0.3576      0.475     -0.753      0.451      -1.288       0.573
C(job)[T.Chief Executive Officer]                             -26.5611   6.72e+04     -0.000      1.000   -1.32e+05    1.32e+05
C(job)[T.Clothing/textile technologist]                         1.1265      0.420      2.683      0.007       0.304       1.949
C(job)[T.Comptroller]                                           0.9117      0.392      2.325      0.020       0.143       1.680
C(job)[T.Copywriter, advertising]                             -25.9503    6.6e+04     -0.000      1.000   -1.29e+05    1.29e+05
C(job)[T.Designer, ceramics/pottery]                           -0.8146      0.458     -1.779      0.075      -1.712       0.083
C(job)[T.Environmental consultant]                             -0.0392      0.443     -0.088      0.930      -0.907       0.829
C(job)[T.Exhibition designer]                                 -24.8205   5.68e+04     -0.000      1.000   -1.11e+05    1.11e+05
C(job)[T.Film/video editor]                                    -0.6376      0.489     -1.303      0.192      -1.596       0.321
C(job)[T.Financial adviser]                                     0.7587      0.418      1.813      0.070      -0.061       1.579
C(job)[T.Historic buildings inspector/conservation officer]    -0.1376      0.449     -0.307      0.759      -1.017       0.742
C(job)[T.IT trainer]                                           -0.3717      0.500     -0.743      0.457      -1.352       0.609
C(job)[T.Immunologist]                                        -26.6898   7.31e+04     -0.000      1.000   -1.43e+05    1.43e+05
C(job)[T.Librarian, public]                                     0.0093      0.428      0.022      0.983      -0.830       0.849
C(job)[T.Magazine features editor]                            -29.5058   8.15e+04     -0.000      1.000    -1.6e+05     1.6e+05
C(job)[T.Materials engineer]                                  -26.9670   6.47e+04     -0.000      1.000   -1.27e+05    1.27e+05
C(job)[T.Mining engineer]                                     -25.9801    7.9e+04     -0.000      1.000   -1.55e+05    1.55e+05
C(job)[T.Musician]                                            -28.1459   6.59e+04     -0.000      1.000   -1.29e+05    1.29e+05
C(job)[T.Naval architect]                                      -0.2741      0.434     -0.631      0.528      -1.125       0.577
C(job)[T.Paramedic]                                           -26.6980    7.2e+04     -0.000      1.000   -1.41e+05    1.41e+05
C(job)[T.Podiatrist]                                            0.4878      0.448      1.089      0.276      -0.390       1.365
C(job)[T.Scientist, audiological]                              -0.4322      0.486     -0.890      0.374      -1.384       0.520
C(job)[T.Scientist, research (maths)]                          -0.1574      0.486     -0.324      0.746      -1.110       0.795
C(job)[T.Sub]                                                   1.5640      0.411      3.801      0.000       0.758       2.370
C(job)[T.Surveyor, land/geomatics]                            -26.5246   6.36e+04     -0.000      1.000   -1.25e+05    1.25e+05
C(job)[T.Systems developer]                                     1.1550      0.388      2.974      0.003       0.394       1.916
C(job)[T.etc]                                                  -0.0891      0.328     -0.272      0.786      -0.732       0.554
C(state)[T.AR]                                                 -0.5162      0.226     -2.280      0.023      -0.960      -0.073
C(state)[T.CA]                                                 -0.5592      0.184     -3.040      0.002      -0.920      -0.199
C(state)[T.FL]                                                 -0.0248      0.200     -0.124      0.901      -0.417       0.368
C(state)[T.GA]                                                 -0.0189      0.195     -0.097      0.923      -0.401       0.363
C(state)[T.IA]                                                 -0.0456      0.201     -0.228      0.820      -0.439       0.347
C(state)[T.IL]                                                 -0.0910      0.185     -0.492      0.623      -0.454       0.272
C(state)[T.IN]                                                  0.3132      0.191      1.637      0.102      -0.062       0.688
C(state)[T.KS]                                                  0.0501      0.224      0.224      0.823      -0.388       0.488
C(state)[T.KY]                                                  0.0566      0.186      0.305      0.761      -0.307       0.421
C(state)[T.LA]                                                 -0.7611      0.265     -2.872      0.004      -1.281      -0.242
C(state)[T.MD]                                                 -0.2892      0.208     -1.388      0.165      -0.698       0.119
C(state)[T.MI]                                                 -0.4503      0.199     -2.265      0.024      -0.840      -0.061
C(state)[T.MN]                                                  0.0548      0.185      0.296      0.767      -0.308       0.417
C(state)[T.MO]                                                 -0.0594      0.185     -0.322      0.747      -0.421       0.302
C(state)[T.MS]                                                  0.3061      0.202      1.519      0.129      -0.089       0.701
C(state)[T.NC]                                                 -0.1944      0.206     -0.944      0.345      -0.598       0.209
C(state)[T.NE]                                                 -0.4790      0.224     -2.139      0.032      -0.918      -0.040
C(state)[T.NJ]                                                 -0.2030      0.210     -0.967      0.334      -0.615       0.209
C(state)[T.NY]                                                  0.0365      0.159      0.230      0.818      -0.274       0.347
C(state)[T.OH]                                                 -0.7635      0.215     -3.548      0.000      -1.185      -0.342
C(state)[T.OK]                                                  0.0078      0.207      0.038      0.970      -0.399       0.414
C(state)[T.PA]                                                 -0.4494      0.176     -2.556      0.011      -0.794      -0.105
C(state)[T.SC]                                                 -0.0510      0.215     -0.237      0.813      -0.472       0.370
C(state)[T.TX]                                                 -0.6474      0.176     -3.674      0.000      -0.993      -0.302
C(state)[T.VA]                                                  0.2194      0.182      1.208      0.227      -0.137       0.575
C(state)[T.WA]                                                 -0.5363      0.280     -1.916      0.055      -1.085       0.012
C(state)[T.WI]                                                  0.1342      0.187      0.719      0.472      -0.232       0.500
C(state)[T.WV]                                                -26.5299   3.65e+04     -0.001      0.999   -7.15e+04    7.15e+04
C(state)[T.WY]                                                 -1.3364      0.383     -3.487      0.000      -2.088      -0.585
C(state)[T.etc]                                                -0.0947      0.147     -0.642      0.521      -0.384       0.194
C(category)[T.food_dining]                                     -0.1103      0.189     -0.584      0.559      -0.480       0.260
C(category)[T.gas_transport]                                    2.1044      0.176     11.950      0.000       1.759       2.450
C(category)[T.grocery_net]                                      1.9824      0.211      9.395      0.000       1.569       2.396
C(category)[T.grocery_pos]                                      3.0695      0.146     20.957      0.000       2.782       3.357
C(category)[T.health_fitness]                                  -0.2250      0.191     -1.179      0.238      -0.599       0.149
C(category)[T.home]                                            -0.3679      0.179     -2.055      0.040      -0.719      -0.017
C(category)[T.kids_pets]                                       -0.3403      0.180     -1.886      0.059      -0.694       0.013
C(category)[T.misc_net]                                         2.6146      0.148     17.632      0.000       2.324       2.905
C(category)[T.misc_pos]                                         0.8335      0.178      4.678      0.000       0.484       1.183
C(category)[T.personal_care]                                   -0.0128      0.178     -0.072      0.943      -0.361       0.335
C(category)[T.shopping_net]                                     2.1176      0.142     14.956      0.000       1.840       2.395
C(category)[T.shopping_pos]                                     1.0024      0.153      6.533      0.000       0.702       1.303
C(category)[T.travel]                                          -4.4261      0.466     -9.503      0.000      -5.339      -3.513
C(gender)[T.M]                                                  0.1248      0.049      2.546      0.011       0.029       0.221
amt                                                             0.3285      0.009     37.388      0.000       0.311       0.346
city_pop                                                        0.0371      0.028      1.339      0.180      -0.017       0.091
age                                                             0.3593      0.024     14.804      0.000       0.312       0.407
unix_time                                                      56.9180      5.608     10.149      0.000      45.926      67.910
distance_km                                                     0.0052      0.023      0.226      0.821      -0.040       0.050
month                                                         -29.2733      2.868    -10.208      0.000     -34.894     -23.653
day                                                            -0.9644      0.093    -10.354      0.000      -1.147      -0.782
hour                                                            0.0970      0.006     16.002      0.000       0.085       0.109
day_of_week                                                     0.0617      0.010      5.959      0.000       0.041       0.082
season                                                          0.8655      0.105      8.212      0.000       0.659       1.072
===============================================================================================================================
"""

In [60]:
significant_pvalues = result.pvalues[result.pvalues < 0.05]

In [61]:
significant_pvalues

Intercept                                   4.167300e-23
C(merchant)[T.fraud_Parisian and Sons]      1.080811e-02
C(city)[T.Andrews]                          4.622186e-02
C(city)[T.Birmingham]                       2.443267e-02
C(city)[T.Meridian]                         1.695549e-02
C(city)[T.etc]                              3.733447e-02
C(job)[T.Clothing/textile technologist]     7.293225e-03
C(job)[T.Comptroller]                       2.009252e-02
C(job)[T.Sub]                               1.438807e-04
C(job)[T.Systems developer]                 2.941776e-03
C(state)[T.AR]                              2.258712e-02
C(state)[T.CA]                              2.366766e-03
C(state)[T.LA]                              4.076274e-03
C(state)[T.MI]                              2.352856e-02
C(state)[T.NE]                              3.243392e-02
C(state)[T.OH]                              3.876374e-04
C(state)[T.PA]                              1.060214e-02
C(state)[T.TX]                              2.384101e-04
C(state)[T.WY]                              4.888658e-04
C(category)[T.gas_transport]                6.458018e-33
C(category)[T.grocery_net]                  5.710502e-21
C(category)[T.grocery_pos]                  1.625384e-97
C(category)[T.home]                         3.992019e-02
C(category)[T.misc_net]                     1.399031e-69
C(category)[T.misc_pos]                     2.896594e-06
C(category)[T.shopping_net]                 1.429302e-50
C(category)[T.shopping_pos]                 6.459604e-11
C(category)[T.travel]                       2.046951e-21
C(gender)[T.M]                              1.090703e-02
amt                                        6.153001e-306
age                                         1.377800e-49
unix_time                                   3.354884e-24
month                                       1.833888e-24
day                                         4.033769e-25
hour                                        1.227930e-57
day_of_week                                 2.535825e-09
season                                      2.169190e-16
dtype: float64

In [66]:
significant_features = significant_pvalues.index
significant_coefficients = result.params[significant_features]
odds_ratios = np.exp(significant_coefficients)

In [69]:
odds_ratios

Intercept                                  1.461035e+123
C(merchant)[T.fraud_Parisian and Sons]      2.457269e+00
C(city)[T.Andrews]                          3.198288e-01
C(city)[T.Birmingham]                       2.576889e+00
C(city)[T.Meridian]                         2.596826e-01
C(city)[T.etc]                              5.012106e-01
C(job)[T.Clothing/textile technologist]     3.084912e+00
C(job)[T.Comptroller]                       2.488578e+00
C(job)[T.Sub]                               4.777693e+00
C(job)[T.Systems developer]                 3.173941e+00
C(state)[T.AR]                              5.967894e-01
C(state)[T.CA]                              5.716758e-01
C(state)[T.LA]                              4.671298e-01
C(state)[T.MI]                              6.374670e-01
C(state)[T.NE]                              6.193944e-01
C(state)[T.OH]                              4.660325e-01
C(state)[T.PA]                              6.379852e-01
C(state)[T.TX]                              5.234242e-01
C(state)[T.WY]                              2.627946e-01
C(category)[T.gas_transport]                8.202329e+00
C(category)[T.grocery_net]                  7.260151e+00
C(category)[T.grocery_pos]                  2.153107e+01
C(category)[T.home]                         6.921616e-01
C(category)[T.misc_net]                     1.366114e+01
C(category)[T.misc_pos]                     2.301347e+00
C(category)[T.shopping_net]                 8.311500e+00
C(category)[T.shopping_pos]                 2.724720e+00
C(category)[T.travel]                       1.196049e-02
C(gender)[T.M]                              1.132975e+00
amt                                         1.388889e+00
age                                         1.432375e+00
unix_time                                   5.237957e+24
month                                       1.935339e-13
day                                         3.812270e-01
hour                                        1.101873e+00
day_of_week                                 1.063649e+00
season                                      2.376294e+00
dtype: float64