In [243]:
import pandas as pd
import numpy as np

In [244]:
pd.set_option('display.max_columns', None)

In [245]:
df = pd.read_csv('./data/fraudTest.csv', index_col=0)

In [246]:
df.head(2)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 555719 entries, 0 to 555718
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  555719 non-null  object
 1   cc_num                 555719 non-null  int64
 2   merchant               555719 non-null  object
 3   category               555719 non-null  object
 4   amt                    555719 non-null  float64
 5   first                  555719 non-null  object
 6   last                   555719 non-null  object
 7   gender                 555719 non-null  object
 8   street                 555719 non-null  object
 9   city                   555719 non-null  object
 10  state                  555719 non-null  object
 11  zip                    555719 non-null  int64
 12  lat                    555719 non-null  float64
 13  long                   555719 non-null  float64
 14  city_pop               555719 non-null  int64
 15  job                    555719 non-null  object
 16  dob                    555719 non-null  object
 17  trans_num              555719 non-null  object
 18  unix_time              555719 non-null  int64
 19  merch_lat              555719 non-null  float64
 20  merch_long             555719 non-null  float64
 21  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(5), object(12)
memory usage: 97.5+ MB

In [248]:
df['is_fraud'].value_counts()

is_fraud
0    553574
1      2145
Name: count, dtype: int64

# Data Dictionary

* `trans_date_trans_time` - 거래 타임스탬프 (날짜 및 시간)
* `cc_num` - 신용카드 번호
* `merchant` - 가맹점 이름
* `category` - 거래 카테고리
* `amt` - 거래 금액
* `first` - 카드 소지자 이름 (이름)
* `last` - 카드 소지자 이름 (성)
* `gender` - 카드 소지자의 성별
* `street` - 카드 소시자 주소
* `city` - 카드 소지자 도시
* `state` - 카드 소지자 주 (state)
* `zip` - 카드 소지자 우편번호
* `lat` - 카드 소지자 위도
* `long` - 카드 소지자 경도
* `city_pop` - 도시 인구수
* `job` - 카드 소지자의 직업
* `dob` - 카드 소지자의 생년월일
* `trans_num` - 거래 고유 번호
* `unix_time` - 유닉스 시간
* `merch_lat` - 가맹점 위도
* `merch_long` - 가맹점 경도
* `is_fraud` - 사기 여부 (1: 사기, 0: 정상)

데이터 제거

- cc_num
- zip
- trans_num
- first, last
- merchant
- street
- unix_time
- state

In [249]:
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])

In [250]:
# trans_date_trans_time 에서 시간, 분, 요일, 년도, 월, 일 추출 

df['month'] = df['trans_date_trans_time'].dt.month
df['day'] = df['trans_date_trans_time'].dt.day
df['hour'] = df['trans_date_trans_time'].dt.hour
df['day_of_week'] = df['trans_date_trans_time'].dt.dayofweek

In [251]:
def season(x):
    if x in [1 ,2 ,3]:
        return 1
    if x in [4 ,5 ,6]:
        return 2
    if x in [7 ,8 ,9]:
        return 3
    if x in [10 ,11 ,12]:
        return 4

df['season'] = df['month'].apply(season)

In [252]:
df.head(2)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,month,day,hour,day_of_week,season
0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0,6,21,12,6,2
1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0,6,21,12,6,2

In [253]:
# dob에서 나이 추출, age는 거래당시의 나이

df['dob'] = pd.to_datetime(df['dob'])

from dateutil.relativedelta import relativedelta

def calculate_age(born, trans_date):
    return relativedelta(trans_date, born).years

df['age'] = df.apply(lambda x: calculate_age(x['dob'], x['trans_date_trans_time']), axis=1)

In [254]:
df.head(2)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,month,day,hour,day_of_week,season,age
0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0,6,21,12,6,2,52
1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0,6,21,12,6,2,30

In [255]:
# 전처리 이후 필요없는 변수(trans_date_trans_time, dob) 제거

df = df.drop(['trans_date_trans_time', 'dob'], axis=1)

In [256]:
df.head(2)

,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,trans_num,unix_time,merch_lat,merch_long,is_fraud,month,day,hour,day_of_week,season,age
0,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0,6,21,12,6,2,52
1,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0,6,21,12,6,2,30

In [257]:
# pvalue가 낮았던 변수 제거

df_non_name = df.drop(['cc_num', 'first', 'last', 'street', 'zip', 'trans_num', 'unix_time', 'merchant', 'city', 'job', 'state', 'city_pop'], axis=1)

In [258]:
df_non_name.head(2)

,category,amt,gender,lat,long,merch_lat,merch_long,is_fraud,month,day,hour,day_of_week,season,age
0,personal_care,2.86,M,33.9659,-80.9355,33.986391,-81.200714,0,6,21,12,6,2,52
1,personal_care,29.84,F,40.3207,-110.4360,39.450498,-109.960431,0,6,21,12,6,2,30

In [259]:
df_non_name.info()

<class 'pandas.core.frame.DataFrame'>
Index: 555719 entries, 0 to 555718
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   category     555719 non-null  object
 1   amt          555719 non-null  float64
 2   gender       555719 non-null  object
 3   lat          555719 non-null  float64
 4   long         555719 non-null  float64
 5   merch_lat    555719 non-null  float64
 6   merch_long   555719 non-null  float64
 7   is_fraud     555719 non-null  int64
 8   month        555719 non-null  int32
 9   day          555719 non-null  int32
 10  hour         555719 non-null  int32
 11  day_of_week  555719 non-null  int32
 12  season       555719 non-null  int64
 13  age          555719 non-null  int64
dtypes: float64(5), int32(4), int64(3), object(2)
memory usage: 55.1+ MB

In [260]:
def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371  # 지구 반지름 (km 단위)
    
    lat1_rad, lon1_rad = np.radians(lat1), np.radians(lon1)
    lat2_rad, lon2_rad = np.radians(lat2), np.radians(lon2)
    
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad
    
    a = np.sin(dlat / 2)**2 + np.cos(lat1_rad) * np.cos(lat2_rad) * np.sin(dlon / 2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    return R * c

In [261]:
df_non_name['distance_km'] = haversine_distance(df_non_name['lat'], df_non_name['long'], df_non_name['merch_lat'], df_non_name['merch_long'])

In [262]:
df_non_name.head(2)

,category,amt,gender,lat,long,merch_lat,merch_long,is_fraud,month,day,hour,day_of_week,season,age,distance_km
0,personal_care,2.86,M,33.9659,-80.9355,33.986391,-81.200714,0,6,21,12,6,2,52,24.561462
1,personal_care,29.84,F,40.3207,-110.4360,39.450498,-109.960431,0,6,21,12,6,2,30,104.925092

In [263]:
df_non_name['category'].unique()

array(['personal_care', 'health_fitness', 'misc_pos', 'travel',
       'kids_pets', 'shopping_pos', 'food_dining', 'home',
       'entertainment', 'shopping_net', 'misc_net', 'grocery_pos',
       'gas_transport', 'grocery_net'], dtype=object)

In [264]:
df_add_distance = df_non_name.drop(['lat', 'long', 'merch_lat', 'merch_long'], axis=1)

In [265]:
df_add_distance.head(2)

,category,amt,gender,is_fraud,month,day,hour,day_of_week,season,age,distance_km
0,personal_care,2.86,M,0,6,21,12,6,2,52,24.561462
1,personal_care,29.84,F,0,6,21,12,6,2,30,104.925092

In [266]:
df_final = df_add_distance.drop(['distance_km'], axis = 1)

In [267]:
df_final.head(2)

,category,amt,gender,is_fraud,month,day,hour,day_of_week,season,age
0,personal_care,2.86,M,0,6,21,12,6,2,52
1,personal_care,29.84,F,0,6,21,12,6,2,30

# 로지스틱회귀 - 통계적 검증

## df_add_distance

In [268]:
from sklearn.preprocessing import StandardScaler

num_cols = ['amt', 'age', 'distance_km']

scaler = StandardScaler()
df_add_distance[num_cols] = scaler.fit_transform(df_add_distance[num_cols])

In [269]:
def reduce_categories(df, col_list, top_n=30):
    df = df.copy()
    for col in col_list:
        top_cats = df[col].value_counts().nlargest(top_n).index
        df[col] = df[col].apply(lambda x: x if x in top_cats else 'etc')
    return df

In [270]:
cat_cols = ['category', 'gender']
df_add_distance = reduce_categories(df_add_distance, cat_cols, top_n=30)

In [271]:
other_cols = ['month', 'day', 'hour']

In [272]:
target = 'is_fraud'
features = num_cols + cat_cols + other_cols
formula = f"{target} ~ " + " + ".join([
    f"C({col})" if col in cat_cols else col for col in features
])

In [273]:
formula

'is_fraud ~ amt + age + distance_km + C(category) + C(gender) + month + day + hour'

In [274]:
df_add_distance.head()

,category,amt,gender,is_fraud,month,day,hour,day_of_week,season,age,distance_km
0,personal_care,-0.424463,M,0,6,21,12,6,2,0.321790,-1.770215
1,personal_care,-0.252337,F,0,6,21,12,6,2,-0.940243,0.989805
2,health_fitness,-0.179353,F,0,6,21,12,6,2,0.149695,-0.584703
3,misc_pos,-0.059605,M,0,6,21,12,6,2,-0.825513,-1.662474
4,travel,-0.422358,M,0,6,21,12,6,2,1.010171,0.969542

In [275]:
df_add_distance.corr(numeric_only=True).abs()

,amt,is_fraud,month,day,hour,day_of_week,season,age,distance_km
amt,1.000000,0.182267,0.000717,0.000829,0.029860,0.003414,0.000550,0.012864,0.000767
is_fraud,0.182267,1.000000,0.011748,0.009203,0.011686,0.009365,0.008153,0.007334,0.000233
month,0.000717,0.011748,1.000000,0.104058,0.004995,0.004090,0.908028,0.007967,0.000382
day,0.000829,0.009203,0.104058,1.000000,0.000161,0.038866,0.139583,0.002373,0.000218
hour,0.029860,0.011686,0.004995,0.000161,1.000000,0.001516,0.006385,0.173695,0.000527
day_of_week,0.003414,0.009365,0.004090,0.038866,0.001516,1.000000,0.012446,0.004135,0.000930
season,0.000550,0.008153,0.908028,0.139583,0.006385,0.012446,1.000000,0.007745,0.000352
age,0.012864,0.007334,0.007967,0.002373,0.173695,0.004135,0.007745,1.000000,0.003165
distance_km,0.000767,0.000233,0.000382,0.000218,0.000527,0.000930,0.000352,0.003165,1.000000

In [276]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

# 가중치 지정
df_add_distance['weights'] = df_add_distance['is_fraud'].apply(lambda x: 258 if x == 1 else 1)

# 모델 생성
model = smf.glm(formula=formula, data=df_add_distance, 
                family=sm.families.Binomial())

# 학습 (weights 적용)
result = model.fit(weights=df_add_distance['weights'])

In [277]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:               is_fraud   No. Observations:               555719
Model:                            GLM   Df Residuals:                   555698
Model Family:                Binomial   Df Model:                           20
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -11679.
Date:                Mon, 30 Jun 2025   Deviance:                       23358.
Time:                        02:07:23   Pearson chi2:                 1.29e+14
No. Iterations:                    12   Pseudo R-squ. (CS):           0.008536
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                        -7.6966      0.198    -38.871      0.000      -8.085      -7.308
C(category)[T.food_dining]       -0.1002      0.189     -0.531      0.595      -0.470       0.269
C(category)[T.gas_transport]      2.0745      0.161     12.845      0.000       1.758       2.391
C(category)[T.grocery_net]        2.0515      0.211      9.737      0.000       1.639       2.464
C(category)[T.grocery_pos]        3.1665      0.146     21.665      0.000       2.880       3.453
C(category)[T.health_fitness]    -0.2339      0.191     -1.228      0.220      -0.607       0.140
C(category)[T.home]              -0.3610      0.179     -2.018      0.044      -0.712      -0.010
C(category)[T.kids_pets]         -0.3318      0.180     -1.841      0.066      -0.685       0.021
C(category)[T.misc_net]           2.7455      0.147     18.632      0.000       2.457       3.034
C(category)[T.misc_pos]           0.8951      0.177      5.045      0.000       0.547       1.243
C(category)[T.personal_care]     -0.0164      0.177     -0.093      0.926      -0.364       0.331
C(category)[T.shopping_net]       2.1832      0.140     15.555      0.000       1.908       2.458
C(category)[T.shopping_pos]       1.0473      0.153      6.865      0.000       0.748       1.346
C(category)[T.travel]            -4.3397      0.472     -9.188      0.000      -5.265      -3.414
C(gender)[T.M]                    0.1276      0.045      2.814      0.005       0.039       0.217
amt                               0.3055      0.008     37.555      0.000       0.290       0.321
age                               0.3653      0.023     16.201      0.000       0.321       0.409
distance_km                       0.0030      0.023      0.133      0.894      -0.041       0.047
month                            -0.1080      0.012     -9.221      0.000      -0.131      -0.085
day                              -0.0213      0.003     -8.449      0.000      -0.026      -0.016
hour                              0.1424      0.005     31.090      0.000       0.133       0.151
=================================================================================================
"""

In [278]:
significant_pvalues = result.pvalues[result.pvalues < 0.05]

In [279]:
significant_pvalues

Intercept                        0.000000e+00
C(category)[T.gas_transport]     9.122977e-38
C(category)[T.grocery_net]       2.101383e-22
C(category)[T.grocery_pos]      4.435170e-104
C(category)[T.home]              4.356508e-02
C(category)[T.misc_net]          1.757563e-77
C(category)[T.misc_pos]          4.526614e-07
C(category)[T.shopping_net]      1.468525e-54
C(category)[T.shopping_pos]      6.653281e-12
C(category)[T.travel]            3.990871e-20
C(gender)[T.M]                   4.900058e-03
amt                             1.149412e-308
age                              4.936216e-59
month                            2.935783e-20
day                              2.926383e-17
hour                            3.279466e-212
dtype: float64

In [280]:
significant_features = significant_pvalues.index
significant_coefficients = result.params[significant_features]
odds_ratios = np.exp(significant_coefficients)

In [281]:
odds_ratios

Intercept                        0.000454
C(category)[T.gas_transport]     7.960673
C(category)[T.grocery_net]       7.779617
C(category)[T.grocery_pos]      23.725307
C(category)[T.home]              0.696953
C(category)[T.misc_net]         15.572240
C(category)[T.misc_pos]          2.447595
C(category)[T.shopping_net]      8.874884
C(category)[T.shopping_pos]      2.849831
C(category)[T.travel]            0.013040
C(gender)[T.M]                   1.136145
amt                              1.357365
age                              1.440930
month                            0.897649
day                              0.978892
hour                             1.153072
dtype: float64